name:                indexable
version:             0.1.0.0
github:              "githubuser/indexable"
license:             BSD3
author:              "Ningji Wei"
maintainer:          "tidues@gmail.com"
copyright:           "2018 Ningji Wei"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis: Containers Subsetting and Slicing
category: Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/tidues/indexable#readme>

dependencies:
- base >= 4.7 && < 5
- split
- containers
- unordered-containers
- text
- hashable
- vector

library:
  source-dirs: src

  #executables:
  #  indexable-exe:
  #    main:                Main.hs
  #    source-dirs:         app
  #    ghc-options:
  #    - -threaded
  #    - -rtsopts
  #    - -with-rtsopts=-N
  #    dependencies:
  #    - indexable

tests:
  indexable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - indexable
